### ISSUE TITLE
Errors in downloads

### ISSUE THREAD

**Issue by nemises** [r00tmebaby/LinkedIn-Downloader#10]
Hi
Firstly thank you for a brilliant tool. 
I am having issues downloading courses it will start downloads miss videos and when I try restart it will fail with "failed to execute script loader.
I'm running Win10  using Python 3.8.0, I've never used or coded in Python and the courses I've been struggling  with are a follows
https://www.linkedin.com/learning/learning-cloud-computing-core-concepts-2
and all the https://www.linkedin.com/learning/paths/master-in-demand-professional-soft-skills sub courses
Thanks 
Nemises

**Comment by r00tmebaby** [comment]
Thanks for the report @nemises. I will try to reproduce the error and come back to you with a solution or suggestion.

**Comment by r00tmebaby** [comment]
Hello, @nemises, I was not able to find a problem with the previous version, but since I had to look at the code again did some updates and new version 0.13 is out there.

Please download the latest version and try again. The chromedriver and browser versions must be the latest. In the latest executable the console is visible.

If you still have a problem, please copy-paste the console log here. I will probably make another video to explain the new features at some point.

**Comment by nemises** [comment]
Hi
Thank you for the fast response and attempt to sort out the issue, I checked my chrome is V78, I also downloaded latest GitHub instance and tried running it again, seems to get through more downloads, however, still seems to "timeout" console02.txt,  I notice the sequence number is missing from the files, download sequence is not the same as the course file sequence, also seems to loop when it finds files it has already down loaded console01.txt.
The new console logging is really helpful and download bars are great, thank you
[console02.txt](https://github.com/r00tmebaby/LinkedIn-Downloader/files/3775600/console02.txt)
[console01.txt](https://github.com/r00tmebaby/LinkedIn-Downloader/files/3775601/console01.txt)
[debug.log](https://github.com/r00tmebaby/LinkedIn-Downloader/files/3775602/debug.log)

**Comment by nemises** [comment]
Hi
Changed to a new internet connection to see if it would make a difference below is the console log and debug
[1027/082400.577:ERROR:exception_snapshot_win.cc(98)] thread ID 11944 not found in process
[1027/232141.726:ERROR:process_reader_win.cc(123)] NtOpenThread: {Access Denied} A process has requested access to an object, but has not been granted those access rights. (0xc0000022)
[1027/232141.727:ERROR:exception_snapshot_win.cc(98)] thread ID 8744 not found in process


###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    26/10/2019          #
#     @version: GUI 0.13                      #
##############################################


DevTools listening on ws://127.0.0.1:49508/devtools/browser/66e21e35-a259-4bd0-a802-ca0eb3e6e09f

[*] Trying to login on LinkedIn[1028/115613.797:INFO:CONSOLE(588)] "No route based profile for route login. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/115613.800:INFO:CONSOLE(588)] "No route based profile for route login. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/115614.113:INFO:CONSOLE(1)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: https://static-exp1.licdn.com/sc/h/br/mhp9ppiaicgf63m0o4qc1fhm (1)
[1028/115618.120:INFO:CONSOLE(98)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: https://static-exp1.licdn.com/sc/p/com.linkedin.helpcenter%3Ahelpcenter-static-content%2B0.3.343/f/%2Fhelpcenter-frontend%2Fartdeco%2Fstatic%2Fjavascripts%2Fartdeco.js (98)
[1028/115619.316:INFO:CONSOLE(3)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: https://content.linkedin.com/etc/designs/gandalf/embed/artdeco.LIHASH7b64997dd33ad06d16e8d01e1666333a.js (3)

[*] Working on course https://www.linkedin.com/learning/body-language-for-leaders-2[1028/115621.509:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/115621.512:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)

[-] File Body Language That Matches Your Words.mp4 already exist. Skipped![1028/115629.969:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)

[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped!
[-] File Body Language In Your Role As A Leader.mp4 already exist. Skipped![1028/115837.607:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)

[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped!
[-] File How Body Language Is Read.mp4 already exist. Skipped![1028/120144.827:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[*] 0001_Cross Cultural Body Language_-:  88%|███████████████████████████████▊    | 20.5M/23.2M [01:08<00:09, 269kB/s][1028/120505.912:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[*] 0001_Cross Cultural Body Language_-: 23.2MB [01:26, 269kB/s]
[1028/120524.395:INFO:CONSOLE(588)] "No route based profile for route course.quiz. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
Traceback (most recent call last):
  File "loader.py", line 376, in <module>
  File "loader.py", line 340, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 530, in find_element_by_tag_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"video"}
  (Session info: headless chrome=78.0.3904.70)

[9956] Failed to execute script loader
[1028/120533.897:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/120913.107:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/121223.479:INFO:CONSOLE(588)] "No route based profile for route course.quiz. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/121232.997:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/121547.723:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/121859.230:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/122157.670:INFO:CONSOLE(588)] "No route based profile for route course.quiz. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/122207.508:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/122525.264:INFO:CONSOLE(588)] "No route based profile for route course.quiz. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)
[1028/122536.360:INFO:CONSOLE(588)] "No route based profile for route course.video. Falling back to global profile learning-web", source: https://static-exp1.licdn.com/sc/h/br/7m57ju1ffk784691lrpqy7pzr (588)

**Comment by r00tmebaby** [comment]
Hi @nemises,

Thanks for the detailed report. Fortunately, I was able to reproduce the error. 

The problem was caused by the Quiz wich some of the chapters have, so the program can not find the video tag and stops. Actually, in the very earliest versions, I have fixed that issue and it's quite strange that it still appears. The only reason can be that I have worked and updated versions that haven't had that issue fixed (worked on old sources). Anyways, please check out the latest 0.14 version with the fix and report.

Also, please remove the old course folder. I have added folder removal function but it is not very reliable (may not work on Linux or macOS), so it's better to remove the downloaded course folder before starting the program. Make sure that you running the program with administrator rights too.

I am looking forward to seeing if the problem has been permanently resolved.

Regard,
r00tme

**Comment by nemises** [comment]
Hi
Hi thanks for the response and assistance, I have also tried to do some work on it (I have never done Python so it was hit and miss) I also found the Quiz issue, I have managed to get a full down load of a course now, I am working with source code and VStudio community. There were a couple of other things 
I changed, if the file existsed I added                         
                        counter += 1
                        download_list.append(video_name1[1])
                        driver.find_element_by_css_selector(".vjs-control.vjs-button.vjs-next-button").click()
                        total_counter += 1
                        temp_counter += 1
As the code never incremented the video name and just stuck in a loop if the file existed
I also removed                         
                       ## main.download(url_temp, save_dir) 
as it seemed to download the file twice

I am still trying to figure out multiple course download as I am getting an error and couple of other things I am getting errors on which I need to figure out

At least I can get whole course downloads now

I have attached a 'working' copy for you to check out please bear with all commented out lines I use them to help me understand the process.

[loaderV1.0.py.txt](https://github.com/r00tmebaby/LinkedIn-Downloader/files/3780915/loaderV1.0.py.txt)

**Comment by r00tmebaby** [comment]
Hi,

Good to hear that you found a solution. There is no problem with the multi-course download (at least I don't have one). You have to paste only the course name like that "https://www.linkedin.com/learning/illustrator-cc-2019-one-on-one-advanced", not like this "https://www.linkedin.com/learning/illustrator-cc-2019-one-on-one-advanced/the-world-s-most-advanced-illustrator-training". Because if the first-course video does not start playing automatically, the program will not find the "next" button. 

This is the approach that I found suitable, but of course, there are many others. So feel free to re-write the program to suit your requirements. In any case after some time, LinkedIn may change something to their website and the program may not work at all. So understanding it is the best way to keep it alive, because I may be able not to keep it updated very often.

You have the idea, source and freedom to use it as you like.
