### ISSUE TITLE
not downloading entire course files

### ISSUE THREAD

**Issue by shadowdragon007** [r00tmebaby/LinkedIn-Downloader#13]
Traceback (most recent call last):
  File "loader.py", line 376, in <module>
  File "loader.py", line 363, in downloader
  File "loader.py", line 67, in remove
ValueError: file C:/Users/Dragoon/Downloads/New folder\\0-Revit 2020 Essential Training For Architecture Metric\\Using Object Styles.mp4 is not a file or dir.
[7408] Failed to execute script loader

i think this might be a chrome loader issue, since, from what i can see, the download only will start after the video starts playing in chrome. so sometimes the next video will not play after the current download is finished.
this happens when i download some courses. this happens especially if the course has more than 30 files.

please if possible also add download resume and
checking whether the files exist, it is complete and then downloading next file.

the current setup just re writes the files

**Comment by r00tmebaby** [comment]
Good suggestions will try to implement them soon.

**Comment by shadowdragon007** [comment]
thank you very much for ur software. 

 this shows up sometimes when i download multiple course, some times it occurs after 1 course other times after 2 or 3. 
[*] 0023_Next Steps_-: 1.69MB [00:03, 463kB/s]
Traceback (most recent call last):
  File "loader.py", line 376, in <module>
  File "loader.py", line 363, in downloader
  File "loader.py", line 67, in remove
ValueError: file C:/Users/Dragoon/Downloads/New folder\\1-Revit Stairs Workshop 2\\Next Steps.mp4 is not a file or dir.
[4852] Failed to execute script loader

this error occurs most of the time after a course is completely downloaded saying the "last filename(Next Steps_)" is not a file or dir even though it has already downloaded the file. u can see that in the above example given. 

error also shows up immediately after the internet get cut and course download is terminated.
so please add the ability to wait for a new connection, and then connect to it and continue the download. 
for example, if the modem connection get cut, then i can connect my phones internet.

i played with timings a little bit and i can download the entire course most of the time.  i also change the user agent most of the time i start a download.

**Comment by r00tmebaby** [comment]
Hi shadowdragon007,

Thanks for the report and suggestions.

I will try to reproduce that error by downloading the same course and come up with a solution/fix or advise.

For the connection suggestion. I think that it is is very possible to put the process on hold if there is no connection for a certain time. From a developing perspective that is not a problem. The question here is not the technical part, but how long the program should wait and also is it really required as a function since cutting an internet connection is not a very common issue these days. I will have to think about it and decide how useful for most people will really that feature be, before deciding to spend time on it.

**Comment by fastmarketo** [comment]
> Good suggestions will try to implement them soon.

Yes, that will be a very important consideration. Wastage of Internet Resources, time and temporary bans from LinkedIn will be avoided.

**Comment by r00tmebaby** [comment]
@shadowdragon007 for the autoplay, I found a simple solution. Whenever you add a course to the list just add "autoplay=true" in the URL and it will start playing automatically, so the program won't be stuck.

Example: **https://www.linkedin.com/learning/revit-2020-essential-training-for-architecture-metric/welcome?autoplay=true&u=36299332**

I will implement that in the next update.
