### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by fastmarketo** [r00tmebaby/LinkedIn-Downloader#14]
![image](https://user-images.githubusercontent.com/6827222/69282910-606db000-0c11-11ea-9a0a-480c88628f1c.png)

![image](https://user-images.githubusercontent.com/6827222/69282928-682d5480-0c11-11ea-9300-4d98e51e5047.png)

It is generating and error.

**Comment by r00tmebaby** [comment]
Use Apply Button
