### ISSUE TITLE
Course Folder Number Issues

### ISSUE THREAD

**Issue by fastmarketo** [r00tmebaby/LinkedIn-Downloader#15]
Use Apply Button

_Originally posted by @r00tmebaby in https://github.com/r00tmebaby/LinkedIn-Downloader/issues/14#issuecomment-556955353_

A minor Issues Courses are numbered only as 1 and 2 see here → 

![image](https://user-images.githubusercontent.com/6827222/69328512-5f6e6a00-0c75-11ea-9934-652f83859cb8.png)

Upgrade Request: Can it also download Exercise Files in future Updates of the software.

**Comment by r00tmebaby** [comment]
Hi, fastmarketo,

Yes, the reason for the markup is actually the course difficulty 0 is basic, 1 is intermediate and 2 is advanced. 

This downloader is based on my other release Linda.com <a href='https://github.com/r00tmebaby/Lynda_Downloader'>**Linda downloader**</a> and it was designed to download the videos with their exercise files, mark the course difficulty, duration, and video resolution. That all info was added to the file name with underscore delimiter.

The downloader was a frame of the bigger picture to fulfill data for a private library build with the website, which I have also released. In fact, you use the downloader to create these folders than by running webserver locally with the website <a href="https://github.com/r00tmebaby/LyndaWebSite">**Linda Website**</a> courses will be displayed, sorted along with all information. That's one of the reasons why you see info.php file in each folder as it holds course information.

In this version, I haven't played that much to implement all the things that were there in the original version with linda.com downloader.

For the exercise request, well, I am currently working on a couple of other projects but as soon I got a bit of free time and desire will do that for sure.

**Comment by fastmarketo** [comment]
Thank you so much for the clarification. All Make sense Now. I will be looking forward to in future that the Excercise file download is included. Is there a way I can get an update when the software is updated?

**Comment by r00tmebaby** [comment]
I think that if you click on the " watch" button and follow my profile, Github will send you everything new added.

**Comment by fastmarketo** [comment]
Thank you so much for the follow-up and support.
