### ISSUE TITLE
Error in 0.16 Version

### ISSUE THREAD

**Issue by fastmarketo** [r00tmebaby/LinkedIn-Downloader#19]
Errors still persists in 0.16 versions → 
![image](https://user-images.githubusercontent.com/6827222/70004577-cb61a400-158c-11ea-806a-62aee25bfde6.png)

**Comment by r00tmebaby** [comment]
Use the delay option to log in manually to LinkedIn and uncheck the login box. You can try the last version 0.16.1 if you wish but the same will apply.
