### ISSUE TITLE
Is it possible to create a login function for organization portal?

### ISSUE THREAD

**Issue by KoichaDev** [r00tmebaby/LinkedIn-Downloader#24]
Hello,

Is it possible to create a function where I can log in as an organization?

**Comment by r00tmebaby** [comment]
You can log in to your organization portal manually and then restart the program.

**Comment by KoichaDev** [comment]
Hello,

Unfortunately no, it gets stuck after just before logging through the organization portal. Here is a URL for the page:

https://imgur.com/NYdSeyQ

When I try to click on the "Sign in with the single-op", then I have to write another username and password which is from my organization. 

On your program, I can only type the username and password which is my original email. My original email is connected to another organization email as well. It requires 2 steps to login obviously which is the original email, and password and the organization email and password.

It would be great if you can add an extra feature to log in on the organization's username and password as well. :)
