### ISSUE TITLE
linkedin - downloader - issue - can't download

### ISSUE THREAD

**Issue by jerry-bazouni** [r00tmebaby/LinkedIn-Downloader#29]
Hi, 

I'm trying to use the app to download a course. 
After the browser login to my account, I got this error and the course is not downloaded.  
Can you please show me how to fix that? 
Thank you.
![image](https://user-images.githubusercontent.com/60333868/73148618-4e2c5880-4111-11ea-8ad3-68c664de9638.png)

**Comment by Frasusan** [comment]
Im also having the same problem

**Comment by r00tmebaby** [comment]
Hi there,

This problem has been described and answered in https://github.com/r00tmebaby/LinkedIn-Downloader/issues/26#
