### ISSUE TITLE
The .Exe file is not running and flagged by the antivirus as trogen horse

### ISSUE THREAD

**Issue by pushpeshkarki2016** [r00tmebaby/LinkedIn-Downloader#31]
When i am running the 0.16.1 exe on my laptop and every time i run that my antivirus is treating it as trojan horse.

**Comment by r00tmebaby** [comment]
There is no trojan on the package but the executable is packed and then sometimes become false-positive warning from AV.

If you feel unsafe and do not trust the developer, just not use the software.
