### ISSUE TITLE
There is no login option tab for the windows executable file

### ISSUE THREAD

**Issue by KoichaDev** [r00tmebaby/LinkedIn-Downloader#42]
Like the title said. There are only 4 tabs on version 0.16.4, but not the last one which is supposed to be login and that has the organization portal as well. Could you please fix this?

**Comment by r00tmebaby** [comment]
Yes, login is removed since it's not needed anymore because LinkedIn implemented Recaptcha is and that is not possible to be bypassed at least not easily. So from version 0.16.5 onwards, only manual login will be supported.

You can start the program then login manually once the browser is opened to your LinkedIn account, then just close the program and start it again. The program should read the saved credentials from the browser directly and open the course without an additional login.

**Comment by KoichaDev** [comment]
It's working perfectly! I didn't know I had to do it. The next problem is that I have added a bunch of URL download options, but it's only downloading a one-course collection of the URL I provided. It doesn't iterate to the next URL when the first URL is finished. 

I am using Mozilla/5.0 (Window NT 10:0; Win64; x64; rv:67) Gecko/20100101 Firefox/67 for the browser.

Any idea of what to do here?

**Comment by r00tmebaby** [comment]
Hmm.. that was problem that I fixed yesterday. Can you re-download the whole package and try again, please?

**Comment by KoichaDev** [comment]
Actually, it's working. I just had to turn the program off and turn on again.  Thank you for developing this fantastic program. I heard that I should delay the download for each  courses. Otherwise, I will get banned. Do you have any experience on this?

**Comment by r00tmebaby** [comment]
Well, you will not get banned, but in the worst scenario blocked for 24 hours. The block if ever appear is bind to the account, not IP. It's hard to tell what is treated as over-request, their information page does not exactly say how many requests are possible for a certain time so, we can only guess. That been said. it may not even depend on the requests but something else.

I have never had blocked account but some people complained about that. So it's hard to say whether the timings will have a positive effect on that matter or not. My advice is to leave it at 0 and see if you get blocked at all. If that ever happens then increase the timings with 2-3 sec and test again.

In the worst scenario, you will have to wait 24 hours to get unblocked, not a huge impact really.
