### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by vinayvjs** [r00tmebaby/LinkedIn-Downloader#52]
[*] Found Lynda Course ID 740366
--------------Ready to Download------------
[*] Working on course https://www.linkedin.com/learning/bluebeam-tips-and-tricks/simultaneous-length-area-and-volume
usage: loader [-h] [-v] [-k] [-u] [-p] [-o] [-d] [-q] [--info] [--sub-only] [--skip-sub] course
loader: error: unrecognized arguments: Learning https://www.lynda.com/Google-Analytics-tutorials/SEO-Foundations/740366-2.html

**Comment by JAqK-01** [comment]
Hey. I faced a similar problem. Check out issue #44 (https://github.com/r00tmebaby/LinkedIn-Downloader/issues/44). It's addressed in his YouTube video from 26th March (linked in that issue #44 thread)

It's a different way of downloading the videos, but it works. All the best.
