### ISSUE TITLE
connection error : make sure your internet connection is working

### ISSUE THREAD

**Issue by sirisha01-sa** [r00tmebaby/LinkedIn-Downloader#56]
![ERROR](https://user-images.githubusercontent.com/63943904/79946360-72d46a00-848d-11ea-8eb5-8b82edf77091.JPG)

**Comment by sirisha01-sa** [comment]
hii, can u please help this error

**Comment by hong1999** [comment]
I have the same problem as you

**Comment by caveman-2020** [comment]
Yes same here.

**Comment by caveman-2020** [comment]
Are you guys using a VPN? Is it possible that our IP is blocked?

**Comment by hong1999** [comment]
> Are you guys using a VPN? Is it possible that our IP is blocked?

no VPN, can't sure the IP was blocked but I can access via browser

**Comment by hong1999** [comment]
Weird problem is I have tried few others downloader same like this which can download exercise file together all has the same problem, but when I use other which just can download the video file but no exercise file they just work fine

**Comment by caveman-2020** [comment]
Which other downloaders are you using and they work? Can you share info?

**Comment by hong1999** [comment]
> Which other downloaders are you using and they work? Can you share info?

https://github.com/ahmedayman4a/LyndaCoursesDownloader  this work but you have to manually download the exercise file

**Comment by caveman-2020** [comment]
Ok think i figured it out but it tells me the same thing ....make sure the internet connection is working...

**Comment by gituseristman** [comment]
I think, the problem is related with cookie and its around but, I don't know python language

**Comment by caveman-2020** [comment]
Hmm so its something inside the Downloader-master... So is there anybody that can assist on this?

**Comment by sirisha01-sa** [comment]
now it's working
