### ISSUE TITLE
LyndaDL Executable's Organization Login

### ISSUE THREAD

**Issue by hong1999** [r00tmebaby/LinkedIn-Downloader#57]
Can you support LyndaDL for organization login? 
And I have the problem with cookies 
cookies error, Request Headers is required

**Comment by gituseristman** [comment]
I think, the problem is related with cookie and its around but, I don't know python language

**Comment by r00tmebaby** [comment]
Hi there,

There is no problem with the provided cookie, it still works. I have just tested it.
Let me explain, the cookie that is in the folder contains public library login data, from my own account that you all use to download content with. So basically if Lynda does not block it you do not do anything else, just start the program and paste the course links that you need to download. That's all.

If you have an account in Lynda.com, right after successful login through normal or organisation portal does not really matter, you can then export the cookie which contains the saved login credentials and replace my cookie file with yours.

To do that you can use a browser extension like https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg for Chrome
