### ISSUE TITLE
LyndaDL Executable's Error

### ISSUE THREAD

**Issue by sirisha01-sa** [r00tmebaby/LinkedIn-Downloader#58]
Hi their,
I hope help this error, i have getting error below, not for all courses, some courses,
error courses list:
https://www.lynda.com/IT-Infrastructure-tutorials/Help-Desk-Handbook-End-Users-Mobile-Networking-Security-Troubleshooting/645047-2.html
https://www.lynda.com/IT-Infrastructure-tutorials/Help-Desk-Handbook-End-Users-PC-Basics-Hardware-Operating-Systems-Applications/645046-2.html

> @r00tmebaby 

: Trying to login using cookies ... 
: Logged in successfully. 
: Downloaded course information .. (done)
 : Trying to logout now... [+] 
: Logged out successfully. ['] 
: Course 'Help Desk Handbook for End Users_ PC Basics Hardware Operating Systems and Applications'. [4] 
: Chapter(s) (9). ['] 
: Lecture(s) (36). 
Traceback (most recent call last)
: File "lynda-dl.py", line 389, in <module> 
File "lynda-dl.py", line 349, in main 
File "lynda-dl.py", line 173, in course_download 
File "lynda\_shared.py", line 136, in course_description 
File "lynda\_shared.py", line 115, in _write_to_file 
FileNotFoundError: [Errno 2] No such file or directory: 'Courses\\Help Desk Handbook for End Users_ PC Basics Hardware Operating Systems and Applications\\Help Desk Handbook for End Users_ PC Basics Hardware Operating Systems and Applications-description.txt' 
[10896] Failed to execute script lynda-dl 

![error](https://user-images.githubusercontent.com/63943904/80300023-bfce7e00-87b6-11ea-845e-66f464a79061.JPG)

**Comment by sirisha01-sa** [comment]
I'm fixed problem

**Comment by lucafeudi** [comment]
How did you solve it?
