### ISSUE TITLE
Downloading Empty directories 

### ISSUE THREAD

**Issue by Frasusan** [r00tmebaby/LinkedIn-Downloader#61]
Hi,
Iam using LyndaDL.exe but Most of the videos in chapters of the course iam downloading are missing or have empy directories

**Comment by Frasusan** [comment]
Hi, 
I have also tried to download using 0.16.2,0.16.3,0.16.4 and 0.16.5 but its failing to download courses

**Comment by r00tmebaby** [comment]
You need a valid login cookie to be able to use LyndaDL.exe. The one that was inside the folder has been blocked by Lynda for obvious reasons.

**Comment by Frasusan** [comment]
How do i get a valid login cookie?

**Comment by jcwh** [comment]
Appreciate your great effort in coming out this program.
How do I generate my own login cookie?
I tried using the export cookies extension of the browser, but the cookies seems to be not compatible with your program. I appreciate if you will be able to share on how to generate my own cookies that is compatible with your program. Thank you.

**Comment by jcwh** [comment]
> You need a valid login cookie to be able to use LyndaDL.exe. The one that was inside the folder has been blocked by Lynda for obvious reasons.

Appreciate your great effort in coming out this program.
How do I generate my own login cookie?
I tried using the export cookies extension of the browser, but the cookies seems to be not compatible with your program. I appreciate if you will be able to share on how to generate my own cookies that is compatible with your program. Thank you.

**Comment by ghost** [comment]
@r00tmebaby I am facing the same,it is downloading Empty directories and I am not a coder but a Tester so I don't know how to generate my own login cookie and after that what to do with that cookie,Kindly help,thanks 

Jessie

**Comment by r00tmebaby** [comment]
With Lynda as mentioned above in my post, you have to have login credentials placed in the cookies.txt file. 
There is a plugin for Chrome browser called cookies.txt (Firefox has too, I guess) which can extract the cookie header after successful login in lynda.com. https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en

Just replace the generated file with those inside the Lynda folder and it should work.

**Comment by r00tmebaby** [comment]
To help you out with cookies, I will create a video in which you will see how to get and use them.

**Comment by ghost** [comment]
Thanks @r00tmebaby , video will be great.
I have a  question will login credentials for Linkedin Learning work ? for this since Lynda is now merged with Linkedin Learning ?I have 15 days of free membership still left.

**Comment by jcwh** [comment]
Thank you.

**Comment by jcwh** [comment]
Will the method to generate the cookie works with Linkedin Learning login as well?

**Comment by ghost** [comment]
@r00tmebaby I used the suggested chrome plugin to create a cookie for the LinkedIn learning portal but the contents of the cookie.txt created is quite different than the contents of the one you have used in Lyndaexecutable.

**Comment by ghost** [comment]
@r00tmebaby Hi Georgiev,Can you please help me with this, my free one month for Linkedin Learning is getting over in a week.

Thanks,
Jassi

**Comment by RemarkableAjay** [comment]
> To help you out with cookies, I will create a video in which you will see how to get and use them.

@r00tmebaby I'll be looking forward to this video, thanks in anticipation!!!

**Comment by shadowdragon007** [comment]
hi, still waiting for that video.

**Comment by ghost** [comment]
@r00tmebaby Hi Georgiev, same here waiting for the video.

**Comment by shegkrye** [comment]
Good afternoon, can you make a video with cookie downloads, please!
