### ISSUE TITLE
executable latest version conclusion folder

### ISSUE THREAD

**Issue by whoami1232123** [r00tmebaby/LinkedIn-Downloader#66]
Thanks for your efforts 
i am trying the executable V2 latest version  and it's working fine until conclusion folder in every course and stop downloading maybe it download from each dictionary one or two videos only 
this is what happens 

https://ibb.co/fkLWFYW

**Comment by whoami1232123** [comment]
i tried both linkedin and lynda they have the same issue so i tried to manually download the conclusion folder and put the video with the same serial so if it checked it find it's already download and skip it and continue  but that failed it;s hang up again

**Comment by r00tmebaby** [comment]
The project is closed for an uncertain time.

I feel sorry to tell you that, but I have no interest left to keep it working any longer. The code is shared, so anyone who wants's to improve it and keep it up to date is very welcome.
