### ISSUE TITLE
Error while running- Chrome version

### ISSUE THREAD

**Issue by ndinh79** [r00tmebaby/LinkedIn-Downloader#68]
Hi, I read and tried many websites for the Linkedin Learning download. I was very happy to find your sharing. I downloaded your latest version. However, when I ran,  an the error came up "this version of ChromeDriver only supports Chrome version 80"
Would you please tell me what I should do next?
Thanks very much.
![Error](https://user-images.githubusercontent.com/66540740/84223727-4659c900-aaa0-11ea-8fd1-63a062a9a117.PNG)

**Comment by r00tmebaby** [comment]
You need the latest chrome driver and chrome browser installed. After downloading replace the old chromedriver.exe file with the new one.

Chrome driver can be downloaded from here https://chromedriver.chromium.org/
