### ISSUE TITLE
Download doesn't start due to different chromedrive.exe version

### ISSUE THREAD

**Issue by vnedelcu** [r00tmebaby/LinkedIn-Downloader#73]
Hi,
When trying to use the Windows executable, with all information provided to the GUI Loader, download just hangs-up and doesn't starts. 
After stopping the process, there is displayed a report saying that the chromedriver.exe supported is release 80, whereas, in my case I have installed Chrome release 85.
Is there any way to reconcile this matter?
Note that "brute force"(a chromerdriver.exe release 85) is not working as the program just doesn't starts at all.
Likely we will have more and more browser releases coming out and therefore I am (just) asking if there is any possibility to automatically keep the GUI loader using the Chrome Driver installed on the machine.
Attached is a screenshot with the error from the app.

![Annotation 2020-08-03 174116](https://user-images.githubusercontent.com/66587761/89194974-c5571380-d5b0-11ea-9fc2-b43c996801ac.jpg)

Thanks.

**Comment by jupmorenor** [comment]
Please see #75
