### ISSUE TITLE
DOWNLOAD ISSUES

### ISSUE THREAD

**Issue by kendy01** [r00tmebaby/LinkedIn-Downloader#74]
I have watched your recent video tutorial on how to download LinkedIn video learning. l have tried to apply that to download from LinkedIn video learning but it is not working. Do l need login to LinkedIn-download before l start the download? If that is the case how do l login? pls help

**Comment by jupmorenor** [comment]
It seems you need to login on Linkedin in your browser.

**Comment by r00tmebaby** [comment]
Exactly as @jupmorenor stated you have to have a Linked in learning account to be able to download any videos. If you use organisation login, please login first and then restart the program so it reads the saved credentials. The other option is to copy the cookie that contains the login credentials and add it. 

Adding cookies is trickier but once done, always works so it is the preferred method.

Regards,
