### ISSUE TITLE
chromedriver not supported

### ISSUE THREAD

**Issue by ESFJx00** [r00tmebaby/LinkedIn-Downloader#75]
![LD LLD](https://user-images.githubusercontent.com/47073959/90293963-fd523680-de8d-11ea-8a17-a9584e3a37a2.PNG)

**Comment by jupmorenor** [comment]
Same issue here but...

I've downloaded the latest chromedriver version to fit the version of my chrome browser at https://chromedriver.chromium.org/
That solves the issue.

**Comment by adegeofroy-exeter** [comment]
You can fix this issue with the following import line in Loader.py, after doing a 'pip install webdriver-manager':
`from webdriver_manager.chrome import ChromeDriverManager`

And change this line:
`driver = webdriver.Chrome("chromedriver.exe", options=build_chrome_options())`
To this:
`driver = webdriver.Chrome(ChromeDriverManager().install(), options=build_chrome_options())`

**Comment by giacomomigliore** [comment]
> 
> 
> You can fix this issue with the following import line in Loader.py, after doing a 'pip install webdriver-manager':
> `from webdriver_manager.chrome import ChromeDriverManager`
> 
> And change this line:
> `driver = webdriver.Chrome("chromedriver.exe", options=build_chrome_options())`
> To this:
> `driver = webdriver.Chrome(ChromeDriverManager().install(), options=build_chrome_options())`

Hi! I changed the file in the Python Source Code folder. How can I make the windows executable use the modified file?
