### ISSUE TITLE
Only Downloading Unlocked Videos (Preview Videos)

### ISSUE THREAD

**Issue by iamaguesthere** [r00tmebaby/LinkedIn-Downloader#78]
It seems that the code is only downloading videos available for preview. The below course is what I tried downloading.  Not sure what the issue is here or if there is a fix to this problem.

https://www.lynda.com/Premiere-Pro-tutorials/Premiere-Pro-2020-Essential-Training/2818085-2.html

**Comment by r00tmebaby** [comment]
You have to use your login credentials (aka to have an account) to be able to download full courses.

Regards
