### ISSUE TITLE
After downloading a file it randomly stops with error "Failed to execute script loader."

### ISSUE THREAD

**Issue by Peenicks** [r00tmebaby/LinkedIn-Downloader#8]
After downloading a couple of videos from a course it stops downloading with the "Fatal Error detected" Failed to execute script loader.

**Comment by Peenicks** [comment]
This happens on the Learning GitHub course and on the Responsive Layout course. After trying out a couple more courses they download a little bit and it stops randomly. I have one course downloaded 12 vids out of 20, other 10 of 15, another near end it just stops.

**Comment by r00tmebaby** [comment]
Change the browser agent. Put your own to avoid blocking from linked learning.
