### ISSUE TITLE
How to input login information for library login?

### ISSUE THREAD

**Issue by tykobrian** [r00tmebaby/LinkedIn-Downloader#81]
I use my New York Public Library card (spoofed) to login to Linkedin Learning. So I don't have a username or password for my account. In that case, what should I input in the login section of the software?

**Comment by r00tmebaby** [comment]
Thanks for the note it is very important to anyone. I also use my university given account to log in, and this is possible when you put a delay on login, using the time to manually log in with your organisation. Restart the program and it should read the saved credentials and directly open your linked in account. Please uncheck the login checkbox otherways the program will attempt to use the standard LinkedIn login URL.

I will look at the programs in the next few days to come up with a more elegant solution so people do not get confused.

Reagards
